# Generated by Django 5.0.4 on 2024-04-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0003_alter_movie_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='lenght',
            new_name='length',
        ),
    ]
