# Generated by Django 5.0.4 on 2024-04-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0004_rename_lenght_movie_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(upload_to='movie_videos/'),
        ),
    ]
