# Generated by Django 5.0.4 on 2024-04-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0005_alter_movie_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Student Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
    ]
