# Generated by Django 5.0.4 on 2024-04-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0006_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
